name: golangci-lint
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: 'v2.3.1' # Use golangci-lint v2 to match config version
          args: --timeout=10m
          skip-cache: true # Disable golangci-lint-action's cache
